<?php

namespace PMG\BingAds\Reporting;

class AdGroupPerformanceReportColumn
{
    const __default = 'AccountName';
    const AccountName = 'AccountName';
    const AccountNumber = 'AccountNumber';
    const AccountId = 'AccountId';
    const TimePeriod = 'TimePeriod';
    const Status = 'Status';
    const CampaignName = 'CampaignName';
    const CampaignId = 'CampaignId';
    const AdGroupName = 'AdGroupName';
    const AdGroupId = 'AdGroupId';
    const CurrencyCode = 'CurrencyCode';
    const AdDistribution = 'AdDistribution';
    const Impressions = 'Impressions';
    const Clicks = 'Clicks';
    const Ctr = 'Ctr';
    const AverageCpc = 'AverageCpc';
    const Spend = 'Spend';
    const AveragePosition = 'AveragePosition';
    const Conversions = 'Conversions';
    const ConversionRate = 'ConversionRate';
    const CostPerConversion = 'CostPerConversion';
    const DeviceType = 'DeviceType';
    const Language = 'Language';
    const DeviceOS = 'DeviceOS';
    const ImpressionSharePercent = 'ImpressionSharePercent';
    const ImpressionLostToBudgetPercent = 'ImpressionLostToBudgetPercent';
    const ImpressionLostToRankAggPercent = 'ImpressionLostToRankAggPercent';
    const QualityScore = 'QualityScore';
    const ExpectedCtr = 'ExpectedCtr';
    const AdRelevance = 'AdRelevance';
    const LandingPageExperience = 'LandingPageExperience';
    const HistoricalQualityScore = 'HistoricalQualityScore';
    const HistoricalExpectedCtr = 'HistoricalExpectedCtr';
    const HistoricalAdRelevance = 'HistoricalAdRelevance';
    const HistoricalLandingPageExperience = 'HistoricalLandingPageExperience';
    const PhoneImpressions = 'PhoneImpressions';
    const PhoneCalls = 'PhoneCalls';
    const Ptr = 'Ptr';
    const Network = 'Network';
    const TopVsOther = 'TopVsOther';
    const BidMatchType = 'BidMatchType';
    const DeliveredMatchType = 'DeliveredMatchType';
    const Assists = 'Assists';
    const Revenue = 'Revenue';
    const ReturnOnAdSpend = 'ReturnOnAdSpend';
    const CostPerAssist = 'CostPerAssist';
    const RevenuePerConversion = 'RevenuePerConversion';
    const RevenuePerAssist = 'RevenuePerAssist';
    const TrackingTemplate = 'TrackingTemplate';
    const CustomParameters = 'CustomParameters';
    const AccountStatus = 'AccountStatus';
    const CampaignStatus = 'CampaignStatus';
    const AdGroupLabels = 'AdGroupLabels';
    const ExactMatchImpressionSharePercent = 'ExactMatchImpressionSharePercent';
    const CustomerId = 'CustomerId';
    const CustomerName = 'CustomerName';
    const ClickSharePercent = 'ClickSharePercent';
    const AbsoluteTopImpressionSharePercent = 'AbsoluteTopImpressionSharePercent';
    const FinalUrlSuffix = 'FinalUrlSuffix';
    const CampaignType = 'CampaignType';
    const TopImpressionShareLostToRankPercent = 'TopImpressionShareLostToRankPercent';
    const TopImpressionShareLostToBudgetPercent = 'TopImpressionShareLostToBudgetPercent';
    const AbsoluteTopImpressionShareLostToRankPercent = 'AbsoluteTopImpressionShareLostToRankPercent';
    const AbsoluteTopImpressionShareLostToBudgetPercent = 'AbsoluteTopImpressionShareLostToBudgetPercent';
    const TopImpressionSharePercent = 'TopImpressionSharePercent';
    const AbsoluteTopImpressionRatePercent = 'AbsoluteTopImpressionRatePercent';
    const TopImpressionRatePercent = 'TopImpressionRatePercent';
    const BaseCampaignId = 'BaseCampaignId';
    const AllConversions = 'AllConversions';
    const AllRevenue = 'AllRevenue';
    const AllConversionRate = 'AllConversionRate';
    const AllCostPerConversion = 'AllCostPerConversion';
    const AllReturnOnAdSpend = 'AllReturnOnAdSpend';
    const AllRevenuePerConversion = 'AllRevenuePerConversion';
    const ViewThroughConversions = 'ViewThroughConversions';
    const Goal = 'Goal';
    const GoalType = 'GoalType';
    const AudienceImpressionSharePercent = 'AudienceImpressionSharePercent';
    const AudienceImpressionLostToRankPercent = 'AudienceImpressionLostToRankPercent';
    const AudienceImpressionLostToBudgetPercent = 'AudienceImpressionLostToBudgetPercent';
    const RelativeCtr = 'RelativeCtr';
    const AdGroupType = 'AdGroupType';


}
